AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploy Application CodePipeline"
Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - uat
      - prod
    Description: Enter dev, uat or prod. Default is dev

  Region:
    Type: String
    Default: us-east-1
    AllowedValues:
      - us-east-1
    Description: This value will be replace by the value of the TemplateConfiguration file. The Region from the cli script need to be on the allowed values list.

Mappings:
  SourceBranchMap:
    dev:
      Branch: dev-deployment
    uat:
      Branch: uat-deployment
    prod:
      Branch: prod-deployment

  SourceChangeMap:
    dev:
      Change: true
    uat:
      Change: false
    prod:
      Change: false

Conditions:
  isDev: !Equals [ !Ref Environment, "dev" ]

Resources:
  ApplicationConnection:
    Type: 'AWS::CodeStarConnections::Connection'
    Properties:
      ConnectionName: !Sub "${Environment}-Application"
      ProviderType: Bitbucket
      Tags:
        - Key: Environment
          Value: !Sub "${Environment}"
        - Key: Package
          Value: application
        - Key: Application
          Value: INFRA

  ApplicationCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Tags:
        - Key: Environment
          Value: !Sub "${Environment}"
        - Key: Package
          Value: application
        - Key: Application
          Value: INFRA
      ArtifactStore:
        Type: S3
        Location:
          Fn::ImportValue: !Sub "${Environment}-${Region}-sergio-codepipelines-project-deployment"
      RestartExecutionOnUpdate:
        !If [ isDev, true, false ]
      RoleArn:
        Fn::ImportValue: !Sub "${Environment}-CodePipelines-Role-Arn"
      Name: Application

      Stages:
        - Name: Source
          Actions:
            -
              Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeStarSourceConnection
              Configuration:
                ConnectionArn: !Ref ApplicationConnection
                DetectChanges: !FindInMap [ SourceChangeMap, !Ref Environment, Change ]
                BranchName: !FindInMap [ SourceBranchMap, !Ref Environment, Branch ]
                FullRepositoryId: projectsergio/ci-cd_with_aws
              OutputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1

        - Name: Application-Cluster
          Actions:
            - Name: Application-Cluster
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: SourceArtifact
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM
                RoleArn:
                  Fn::ImportValue: !Sub "${Environment}-CodePipelines-Role-Arn"
                StackName: !Sub "${Environment}-app-cluster"
                TemplatePath: !Sub "SourceArtifact::Templates/application/app-cluster_cloudformation.yaml"
              RunOrder: 1
              Region: !Sub ${Region}

        - Name: Welcome-Api
          Actions:
            - Name: Welcome-Api
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: SourceArtifact
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM
                RoleArn:
                  Fn::ImportValue: !Sub "${Environment}-CodePipelines-Role-Arn"
                StackName: !Sub "${Environment}-app"
                TemplatePath: !Sub "SourceArtifact::Templates/application/welcome-api_cloudformation.yaml"
              RunOrder: 1
              Region: !Sub ${Region}