AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploy Core-Network CodePipeline"
Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - uat
      - prod
    Description: Enter dev, uat or prod. Default is dev

  Region:
    Type: String
    Default: us-east-1
    AllowedValues:
      - us-east-1
    Description: This value will be replace by the value of the TemplateConfiguration file. The Region from the cli script need to be on the allowed values list.

Mappings:
  SourceBranchMap:
    dev:
      Branch: dev-deployment
    uat:
      Branch: uat-deployment
    prod-:
      Branch: prod-deployment

  SourceChangeMap:
    dev:
      Change: true
    uat:
      Change: false
    prod:
      Change: false

Conditions:
  isDev: !Equals [ !Ref Environment, "dev" ]

Resources:

  CoreNetworkConnection:
    Type: 'AWS::CodeStarConnections::Connection'
    Properties:
      ConnectionName: !Sub "${Environment}-Core-Network"
      ProviderType: Bitbucket
      Tags:
        - Key: Environment
          Value: !Sub "${Environment}"
        - Key: Package
          Value: core-network
        - Key: Application
          Value: INFRA

  CoreNetworkCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Tags:
        - Key: Environment
          Value: !Sub "${Environment}"
        - Key: Package
          Value: core-network
        - Key: Application
          Value: INFRA
      ArtifactStore:
        Type: S3
        Location:
          Fn::ImportValue: !Sub "${Environment}-${Region}-sergio-codepipelines-project-deployment"
      RestartExecutionOnUpdate:
        !If [ isDev, true, false ]
      RoleArn:
        Fn::ImportValue: !Sub "${Environment}-CodePipelines-Role-Arn"
      Name: Core-Network

      Stages:
        - Name: Source
          Actions:
            -
              Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeStarSourceConnection
              Configuration:
                ConnectionArn: !Ref CoreNetworkConnection
                DetectChanges: !FindInMap [ SourceChangeMap, !Ref Environment, Change ]
                BranchName: !FindInMap [ SourceBranchMap, !Ref Environment, Branch ]
                FullRepositoryId: projectsergio/CI-CD_with_AWS
              OutputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1

        - Name: VPC
          Actions:
            - Name: VPC
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: SourceArtifact
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM
                RoleArn:
                  Fn::ImportValue: !Sub "${Environment}-CodePipelines-Role-Arn"
                StackName: !Sub "${Environment}-vpc"
                TemplateConfiguration: !Sub "SourceArtifact::Template-Configuration/${Environment}/TemplateConfiguration.json"
                TemplatePath: !Sub "SourceArtifact::Templates/core-network/vpc_cloudformation.yaml"
              RunOrder: 1
              Region: !Sub ${Region}

        - Name: Network-ACLs
          Actions:
            - Name: 1a-network-acl
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: SourceArtifact
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM
                RoleArn:
                  Fn::ImportValue: !Sub "${Environment}-CodePipelines-Role-Arn"
                StackName: !Sub "${Environment}-1a-network-acl"
                TemplateConfiguration: !Sub "SourceArtifact::Template-Configuration/${Environment}/TemplateConfiguration.json"
                TemplatePath: !Sub "SourceArtifact::Templates/core-network/1a-network-acl_cloudformation.yaml"
              RunOrder: 1
              Region: !Sub ${Region}
              
            - Name: 1b-network-acl
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: SourceArtifact
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM
                RoleArn:
                  Fn::ImportValue: !Sub "${Environment}-CodePipelines-Role-Arn"
                StackName: !Sub "${Environment}-1b-network-acl"
                TemplateConfiguration: !Sub "SourceArtifact::Template-Configuration/${Environment}/TemplateConfiguration.json"
                TemplatePath: !Sub "SourceArtifact::Templates/core-network/1b-network-acl_cloudformation.yaml"
              RunOrder: '2'
              Region: !Sub ${Region}

        - Name: Subnets
          Actions:
            - Name: Subnet1a
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: SourceArtifact
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM
                RoleArn:
                  Fn::ImportValue: !Sub "${Environment}-CodePipelines-Role-Arn"
                StackName: !Sub "${Environment}-1a-subnet"
                TemplateConfiguration: !Sub "SourceArtifact::Template-Configuration/${Environment}/TemplateConfiguration.json"
                TemplatePath: !Sub "SourceArtifact::Templates/core-network/1a-subnet_cloudformation.yaml"
              RunOrder: 1
              Region: !Sub ${Region}

            - Name: Subnet1b
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: SourceArtifact
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM
                RoleArn:
                  Fn::ImportValue: !Sub "${Environment}-CodePipelines-Role-Arn"
                StackName: !Sub "${Environment}-1b-subnet"
                TemplateConfiguration: !Sub "SourceArtifact::Template-Configuration/${Environment}/TemplateConfiguration.json"
                TemplatePath: !Sub "SourceArtifact::Templates/core-network/1b-subnet_cloudformation.yaml"
              RunOrder: '2'
              Region: !Sub "${Region}"

        - Name: NAT-Gateway
          Actions:
            - Name: NAT-Gateway
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: SourceArtifact
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM
                RoleArn:
                  Fn::ImportValue: !Sub "${Environment}-CodePipelines-Role-Arn"
                StackName: !Sub "${Environment}-1a-natgateway"
                TemplateConfiguration: !Sub "SourceArtifact::Template-Configuration/${Environment}/TemplateConfiguration.json"
                TemplatePath: !Sub "SourceArtifact::Templates/core-network/1a-natgateway_cloudformation.yaml"
              RunOrder: 1
              Region: !Sub ${Region}