AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::SecretsManager-2020-07-23
Description: SIX  postgresql database users
Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - uat
      - prod
    Description: Enter dev, uat or prod. Default is dev
  Region:
    Type: String
    Default: us-east-1
    AllowedValues:
      - us-east-1
      - eu-west-1
      - eu-central-1
      - eu-central-2
    Description: 'This value will be replace by the value of the TemplateConfiguration file'

Conditions:
  isProd: !Equals  [!Ref Environment, prod]
  isDev: !Equals  [!Ref Environment, dev]

Resources:
  AuroraPostgresqlUserCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${Environment}-analystDbUserCredentials
      Description: Database credentials for analyst user
      GenerateSecretString:
        SecretStringTemplate: '{"username": "analyst"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\'

  AuroraPostgresqlUserCredentialsAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref AuroraPostgresqlUserCredentials
      TargetId: !Sub arn:aws:rds:${AWS::Region}:${AWS::AccountId}:cluster:${Environment}-aurora-postgresql-serverless-db-cluster
      TargetType: AWS::RDS::DBCluster

  AuroraPostgresqlUserCredentialsRotationSchedule:
    Type: AWS::SecretsManager::RotationSchedule
    Properties:
      SecretId: !Ref AuroraPostgresqlUserCredentials
      HostedRotationLambda:
        RotationType: "PostgreSQLSingleUser"
        RotationLambdaName: !Sub ${Environment}-AuroraPostgresqlUserCredentials-SecretsManagerRotation
        VpcSecurityGroupIds:
          Fn::ImportValue: !Sub ${Environment}-rds-access
        VpcSubnetIds:
            - Fn::ImportValue:
                  !Sub "${Environment}InternalSubnet-${Region}a"
      RotationRules:
        AutomaticallyAfterDays: 30

        
